= DigitalPersona Card API v1
:table-caption!:

toc::[]


== Overview

As a part of DigitalPersona Access Management API (DPAM), the `@digitalpersona/card` library provides a Javascript API allowing to communicate
with card readers from web browsers.

WARNING: **This v1 API is discontinued!** For new applications, please use the latest v2 API which provides a simpler async interface instead of the
event-based one.

IMPORTANT: The API is designed to be used in a browser environment only! It is not a NodeJS library!

== Installation

```shell
> npm install @digitalpersona/card@v1 @digitalpersona/websdk
```

IMPORTANT: You must use the "@v1" tag to install this version of the package.
Without the tag, the latest v2 version will be installed.

Once the package is installed, it can be imported into your browser application.

The `@digitalpersona/card@v1` only provides a legacy IIFE module.
No modern ESM module is provided.

The IIFE module works in legacy and/or for simple "build-less" applications,
with no requirements for bundling and dead code elimination. The IIFE module
must be imported using the HTML `<script>` tag. You can use a CDN such unpkg.com:
`<script src="https://unpkg.com/@digitalpersona/card@v1/dist/card.sdk.js">`.

The IIFE module adds a global `Card.WebApi` property to the `window` object.
When using bundlers such as Rollup and Webpack, the `"Card.WebApi"` object must be
added to the list of "globals", and the `"@digitalpersona/card"` must be added
to the list of "external" modules, so it will not be bundled into the final
output.

IMPORTANT: The library has a peer dependency on the `@digitalpersona/websdk` package,
  which provides a JavaScript interface to the native API.
  Make sure the `@digitalpersona/websdk` is also installed as a runtime dependency
  in your project. The `@digitalpersona/websdk` is currently available only
  as an IIFE module, so you also must import it using a `<script>` tag,
  and add `"WebSdk"` to the list of "globals", and add `"@digitalpersona/websdk"`
  to the list of "external" modules to prevent bundling.

If you are using a vanilla Javascript application, you can add the following
`script` tag to your HTML page:

[separator=¦]
|===
a¦
.index.html
[source,html]
----
<script type="text/javascript" src="scripts/websdk.client.ui.js"></script>
<script type="text/javascript" src="scripts/card.sdk.js"></script>
<script type="text/javascript" src="index.js"></script>
----

.index.js
[source,js]
----
/// <reference types="@digitalpersona/websdk" />
/// <reference types="@digitalpersona/card" />

class CardSigninControl
{
  constructor() {
    this.api = new Card.WebApi();
    this.api.onCardInserted = this.onCardInserted.bind(this);
    ...
  }

  async startCapture() {
    try {
      await this.api.subscribe();
      ...
    } catch(e) { ... }
  }

  async stopCapture() {
    try {
      await this.api.unsubscribe();
      ...
    } catch(e) { ... }
  }

  async onCardInserted(data) {
   ...
  }
}
...

----
|===


If you are using Angular project (Typescript + bundler), you can
import the library as follows:

[separator=¦]
|===
a¦
.angular.json
[source,json]
----
{
  "projects": {
    "my-app": {
      "architect": {
        "build": {
          "options": {
            "preserveSymlinks": true,  // https://github.com/angular/angular/issues/54147
            "index": "src/index.html",
            "browser": "src/main.ts",
            "scripts": [
              "./node_modules/@digitalpersona/websdk/dist/websdk.client.ui.js",
              "./node_modules/@digitalpersona/card/dist/card.sdk.js"
            ]
          }
        },
      }
    }
  }
}
----

.app.component.ts
[source,typescript]
----
/// <reference types="@digitalpersona/websdk" />
/// <reference types="@digitalpersona/card" />

const api = new Card.WebApi();
...

----
|===

NOTE: The `projects.my-app.architect.build.scripts` property in the `angular.json`
is the https://angular.dev/reference/configs/workspace-config#build-target[Angular's way]
to bundle external modules such as `@digitalpersona/websdk` and `@digitalpersona/card`
as if they would be loaded with the `<script>` tag.

NOTE: The `/// <reference types="..." />` needs to be added avoid TypeScript typing errors.
You may also need to set https://www.typescriptlang.org/tsconfig/#moduleResolution[`"moduleResolution": "bundler"`]
in your `tsconfig.json`, to tell TypeScript to use the modern module resolution algorithm.

== Usage

In a typical use case, users navigate to a logon (or card enrollment) page
where they are presented with a card logon/enrollment UI. The page either
starts the card capture process automatically or allows the user to start and
cancel the card capture process by clicking UI elements such as buttons.

In your card sign-in controller class, create an instance of a `Card.WebApi`
class and subscribe to its events:

[separator=¦]
|===
a¦

.cardSignin.component.ts
[source,typescript]
----
// NOTE: Make sure you import only typings here, not a code!
// Also make sure this is not a NodeJS module. Card API is a browser-only library!

/// <reference types="@digitalpersona/websdk" />
/// <reference types="@digitalpersona/card" />

export class CardSignin
{
    constructor() {
      this.api = new Card.WebApi();
      this.api.onReaderConnected = this.onReaderConnected.bind(this);
      this.api.onReaderDisconnected = this.onReaderDisconnected.bind(this);
      this.api.onCardInserted = this.onCardInserted.bind(this);
      this.api.onCardRemoved = this.onCardRemoved.bind(this);
      this.api.onCommunicationFailed = this.onCommunicationFailed.bind(this);
      this.capturing = false;
    }

    // Event handlers
    async onReaderConnected(event) { ... }
    async onReaderDisconnected(event) { ... }
    async onCardInserted(event) { ... }
    async onCardRemoved(event) { ... }
    async onCommunicationFailed(event) { ... }

    ...
}
----
|===

The Card API requires a HID DigitalPersona Agent running on a client machine.
This agent provides a secure communication channel between a browser and a card
device driver.

The DigitalPersona Agent is a native Microsoft Windows application and is a part of
HID DigitalPersona clients such as:

* HID DigitalPersona Workstation
* HID DigitalPersona Kiosk
* HID Authentication Device Client (ADC, previously Lite Client)

If you expect that your users may not have any of the HID DigitalPersona clients installed, provide a https://digitalpersona.hidglobal.com/lite-client/[link
to the HID ADC download] in a reader communication error:


[separator=¦]
|===
a¦

.cardSignin.component.html
[source,html]
----
<div class="reader-communication-error">
  Cannot connect to you fingerprint device.
  Make sure the device is connected.
  If you do not use HID DigitalPersona Workstation or Kiosk,
  you may need to download and install the
  <a href="https://digitalpersona.hidglobal.com/lite-client/">
    HID Authentication Device Client
  </a>.
</div>
----

.cardSignin.component.ts
[source,typescript]
----
class CardSignin
{
    ...
    async onCommunicationFailed(event) {
        // TODO: display the `.reader-communication-error` block
        ...
    }
}
----
|===


To start capturing card data, start listening for card events using the `subscribe()` method. To stop listening, use the `unsubscribe()` method:

[separator=¦]
|===
a¦

[source,typescript]
----
class CardSignin {
    ....
    async startCapture() {
        try {
            await this.api.subscribe();
            this.capturing = true;
        } catch (error) {
            this.handleError(error);
        }
    }

    async stopCapture() {
        if (!this.capturing) return;
        try {
            await this.api.unsubscribe();
        } catch (error) {
            this.handleError(error);
        }
        this.capturing = false;
    }
}
----
|===

When a card is presented, first detect its type, then handle the card depending
on the card type and intent of the capture (enrollment or authentication).

NOTE: Smart cards require users to enter the card PIN, while contactless and
proximity cards can be used without entering any code.

[separator=¦]
|===
a¦

[source,typescript]
----
class CardSignin {
    ...
    async onCardInserted(event: CardInserted)
    {
        try {
            // get card type and other info
            const card =
                await this.api.getCardInfo(event.deviceId);
            if (!card) return; // the card was removed too early

            // for smartcards, obtain PIN from the user first
            var pin;
            if (card.Type == Card.CardType.Contact) {
                pin = await this.promptPIN();
            }

            // depending on the purpose of the card capture
            // (enrollment of authentication), read corresponding card data
            if (this.enrolling) {
                const cardData =
                    await this.api.getCardEnrollData(card.Reader, pin);
                await this.enrollCard(cardData);
                ...

            } else {
                const cardData =
                    await this.api.getCardAuthData(card.Reader, pin);
                this.token = await this.signin(cardData);
                ...
            }

        }
        catch (error) {
            this.handleError(error);
        }
    }

    async promptPIN() {
        // TODO: show UI prompting the user to enter the smartcard PIN
    }

    async enrollCard(cardData) { ... }

    async signin(cardData, cardType) {
        // TODO: use the cardData to authenticate or identify the user.
        // NOTE: smartcards support only authentication.
    }
}
----
|===

In addition, using the Card API, you can:

* Enumerate all card readers in the system using the `enumerateReaders` method.
* Enumerate cards on a specific reader using the `enumerateCards` method.
* Read the UID of a card on a specific reader using the `getCardUid` method.
* Read an object name of a card on a specific reader using the `getCardObjectName` method. The object name is a base64-encoded GUID of an object stored in the user's
record in the database (AD or LDS).
