= Design
:table-caption!:

This document describes the design of the Card Web API.

toc::[]

== Overview

The API design is largely motivated by the standard
https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API[Fetch API], which
provides a very simple interface to retrieve data using a Promise-like type,
and allows request cancellation via a standard
https://developer.mozilla.org/en-US/docs/Web/API/AbortController[`AbortController`]
class.

IMPORTANT: The API is designed to be used in a browser environment only! It is not a NodeJS library!

== Installation

```
> npm install @digitalpersona/card
```

Once the package is installed, it can be imported into your browser application.

The `@digitalpersona/card` provides both a legacy IIFE module and a modern ESM module.

The ESM module should be imported using the modern `import` statement. This is a
preferred way for modern applications.

The IIFE module is provided for legacy and/or for simple "build-less" applications,
with no requirements for bundling and dead code elimination. The IIFE module
must be imported using the HTML `<script>` tag. You can use a CDN such as unpkg.com:
`<script src="https://unpkg.com/@digitalpersona/card@latest/dist/index.js">`.

The IIFE module adds a global `dp.card` property to the `window` object.
When using bundlers such as Rollup, Webpack, etc, the `"dp.card"` object must be
added to the list of "globals", and the `"@digitalpersona/card"` must be added
to the list of "external" modules, so it will not be bundled into the final
output.

IMPORTANT: The library has a peer dependency on the `@digitalpersona/websdk` package,
  which provides a JavaScript interface to the native API.
  Make sure the `@digitalpersona/websdk` is also installed as a runtime dependency
  in your project. The `@digitalpersona/websdk` is currently available only
  as an IIFE module, so you also must import it using a `<script>` tag,
  add `"WebSdk"` to the list of "globals", and add `"@digitalpersona/websdk"` to the list of "external" modules to prevent bundling.

If you are using a vanilla Javascript application, you can add the following
`script` tag to your HTML page:

[separator=¦]
|===
a¦
.index.html
[source,html]
----
<script type="text/javascript" src="scripts/websdk/websdk.client.ui.js"></script>
<script type="text/javascript" src="scripts/card/index.js"></script>
<script type="text/javascript" src="index.js"></script>
----

.index.js
[source,js]
----
const { capture } = dp.card;
...
const cardData = await capture(...);
----
|===


If you are using Angular project (Typescript + bundler), you can
import the library as follows:

[separator=¦]
|===
a¦
.angular.json
[source,json]
----
{
  "projects": {
    "my-app": {
      "architect": {
        "build": {
          "options": {
            "preserveSymlinks": true,  // https://github.com/angular/angular/issues/54147
            "index": "src/index.html",
            "browser": "src/main.ts",
            "scripts": ["./node_modules/@digitalpersona/websdk/dist/websdk.client.ui.js"]
          }
        },
      }
    }
  }
}
----

.app.component.ts
[source,typescript]
----
/// <reference path="../node_modules/@digitalpersona/websdk/dts/websdk.client.d.ts" />

import { capture } from '@digitalpersona/card';
...
const cardData = await capture(...);
----
|===

NOTE: The `projects.my-app.architect.build.scripts` property in the `angular.json`
is the https://angular.dev/reference/configs/workspace-config#build-target[Angular's way]
to bundle external modules such as `@digitalpersona/websdk`, as if they would be
loaded with the `<script>` tag.

NOTE: The `/// <reference path=".../websdk.client.d.ts" />` may need to be added avoid TypeScript typing errors.
You may also need to set `"moduleResolution": "bundler"` in your `tsconfig.json`, for correct type checking of imports.


== Usage

In a typical use case, users navigate to a logon (or card enrollment) page where they are presented with a card logon/enrollment UI. The page either
starts the card capture process automatically or allows the user to start and
cancel the card capture process by clicking UI elements such as buttons.

Below is a scenario where a logon page allows the user to initiate the card
capture process by clicking on a btn:[Capture] button (`captureButton`)
and stop it by clicking a btn:[Cancel] button (`cancelButton`); the card type
is limited to Contactless Writable. When the capture is complete, a card logon/enrollment
data is returned for further processing. During the capture process, user will
see feedback messages, prompting to place a card on a reader or notifying about
capture completion/errors.

.Example
[separator=¦]
|===
a¦
[source,typescript]
----
import { Purpose, CardType, Feeedback, FeedbackMessage, ApiError, ErrorMessage, capture } from '@digitalpersona/card';

...

const startButton = document.getElementById('start');
const cancelButton  = document.getElementById('cancel');
const feedbackView = document.getElementById('feedback');
const errorView = document.getElementById('error');

// [Capture] button click handler
startButton.onclick = async () =>
{
    const ac = new AbortController();               // <1>

    try {
        setCaptureActive(true, ac);                 // <2>
        updateFeedbackView()
        updateErrorView()

        const data = await capture("auth", {        // <3>
            cardType: "CW",
            signal: ac.signal,
            onFeedback: updateFeedbackView
        });

        const token = await authenticate(data);     // <4>
    }
    catch(e) {
        updateErrorView(e);                         // <5>
    }
    finally {
        setCaptureActive(false);                    // <6>
        updateFeedbackView()
    }
};

// Update state of [Capture] and [Cancel] buttons in a consistent way,
// and attach a cancellation handler.
function setCaptureActive(capturing: boolean, ac?: AbortController)
{
    startButton.disabled = capturing;               // <7>
    cancelButton.disabled = !capturing;             // <8>
    cancelButton.onclick = (capturing && ac) ?
        () => ac.abort() : null                     // <9>
}

// Update a user feedback view
function updateFeedbackView(feedback?: Feedback) {
    feedbackView.hidden = !feedback;
    feedbackView.innerText = translate(feedback) || '';
}

// Update an error view
function updateErrorView(error?: ApiError) {
    errorView.hidden = !error;
    errorView.innerText = translate(error) || '';
}

// Translate feedbacks/errors to human-readable prompts/notifications.
// NOTE: this example show use of the Angular's `$localize` taggged
// template literals for API message localization; other frameworks
// may use their own localization serices.
function translate({
    message?: FeedbackMessage | ErrorMessage | string,
    code?: number
}){
    if (!message) return "";
    switch(message) {
        // feedbacks
        case "Starting"             : return $localize`Starting...`;
        case "Paused"               : return $localize`Paused, click on the page to resume.`;
        case "ConnectReader"        : return $localize`Connect a card reader.`;
        case "UseCard"              : return $localize`Tap a card.`;
        case "UseDifferentCard"     : return $localize`Use a different card.`;
        case "UseDifferentCardType" : return $localize`Use a card of different type.`;
        case "UseSingleCard"        : return $localize`Use a single card.`;
        // errors
        case "BadVersion"           : return $localize`Incompatible client version.`;
        case "BadConnection"        : return $localize`Connection failure.`;
        case "BadResponse"          : return $localize`Service failure.`;
        case "Aborted"              : return $localize`The operation was aborted.`;
        // Show unknown platform-generated messages with codes "as-is".
        // The message will be in a system locale, not a browser locale.
        default:
            return `${message || `Oops!`} Code: ${code || "N/A"}`;
    }
}
----

'''
<1> prepare an `AbortController` object to be able to cancel the capture request
    and create a handler for a btn:[Click] button
<2> update the UI to indicate a capture process is started
<3> start the capture flow, passing the purpose, card type, an abort signal
    and feedback handler reference.
<4> receive card data and use it for authentication.
<5> handle errors.
<6> update the UI to indicate the capture process is stopped.
<7> disable the btn:[Capture] button when capturing to prevent second click;
    enable otherwise.
<8> enable the btn:[Cancel] button when capturing; disable otherwise.
<9> attach the `AbortController` to the btn:[Cancel] when capturing
|===

For more complete examples of a working code, see the link:../../samples[code samples].


== API

== Functions

'''''''''''''''''''''
[[capture, capture]]
==== `capture`

The `capture` function starts a card data capture process, returning a promise
that is fulfilled once the user presents a card of an eligible type, and the
card data is successfully read.

.Definition
[separator=¦]
|===
a¦
[source,typescript]
----
async function capture(
    purpose: Purpose,
    options?: CaptureOptions
): Promise<CaptureResult>
----
|===


.Parameters
[cols="^1,^1,^1,10"]
|===
| Name | Type | Specs | Description

| purpose
| <<Purpose>>
| mandatory
| A <<Purpose>> value, showing what the retrieved card data will be used for.
    This value affects what data will be returned in the <<CaptureResult>>'s `Data` property.

| options
| <<CaptureOptions>>
| optional
| An optional <<CaptureOptions>> object containing optional settings that
    you want to apply to the capture process, such as a desired <<CardType, card type>>,
    a user <<FeedbackHandler,feedback>> callback function, an inactivity timeout,
    an https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal[`AbortSignal`]
    for operation cancellation, or additional communication channel options.
|===

.Return value
[cols="1,1"]
|===
^| Success ^| Failure

| A promise which resolves to a <<CaptureResult>> object
| A rejected promise with <<ApiError>> object.
|===

When the promise is resolved to the <<CaptureResult>> object, its <<CardType, Type>>
property indicates the type of the card presented, and the <<CardType, Data>> property
contains a string which can be passed to the authentication server directly, as
an opaque blob. The string is base64url-encoded JSON object containing either
<<EnrollmentData>> or <<AuthenticationData>>, depending on the `purpose` value

In case of abort using an `AbortController.abort()` call, the promise is rejected
with <<ApiError>> whose `message` property is set to <<ErrorMessage, `Aborted`>> value.

=== Data types

This chapter describes Card API data types used or returned by the <<capture>> function.

'''''''''''''''''''
[[Purpose, Purpose]]
==== `Purpose`

The `Purpose` value MUST be passed to the <<capture>> function as a first parameter.
The value defines what scenario the captured card data is about to be used and what
data will be returned in the <<CaptureResult>>'s `Data` property.

.Definition
[separator=¦]
|===
a¦
[source,typescript]
----
type Purpose = "enroll" | "auth"
----
|===

The requested purpose affects what data will be returned in the `<<CaptureResult>>.Data` as a base64url-encoded string.

.Values
[%autowidth]
|===
| Name | Description

|"enroll"
| Card data will be used for enrollment. The `<<CaptureResult>>.Data` will contain base64url-encoded <<EnrollmentData>>.

| "auth"
| Card data will be used for authentication. The `<<CaptureResult>>.Data` will contain base64url-encoded <<AuthenticationData>>.
|===

''''''''''''''''''''''''''''''''''
[[CaptureOptions, CaptureOptions]]
==== `CaptureOptions`

The `CaptureOptions` object can be passed to the <<capture>> function as an optional second parameter `options`.

.Definition
[separator=¦]
|===
a¦
[source,typescript]
----
interface CaptureOptions {
    readonly cardType?: CardType
    readonly inactivityTimeout?: number
    readonly signal?: AbortSignal
    readonly onFeedback?: FeedbackHandler
    readonly channelOptions?: WebSdk.WebChannelOptionsData
    readonly debug?: boolean
}
----
|===

.Properties
[cols="^1,^1,^1,10"]
|===
| Name | Type | Specs | Description

| cardType
| <<CardType>>
| optional
| Defines which cart types should be accepted.
    If not provided or empty, any card type will be accepted.

| inactivityTimeout
| `number`
| optional
| An allowed inactivity period in seconds when no activity
    (events or feedback) is received from the card engine.
    Default value is infinite.
    If inactivity period is expires, the capture process will be aborted with
    the `<<ErrorMessage, Timeout>>` <<ApiError>>

| signal
| `AbortSignal`
| optional
| A signal provided by the `AbortController.signal`.
    The `AbortController.abort()` function can be used to cancel the capture operation.

| onFeedback
| <<FeedbackHandler>>
| optional
| A callback function to be called when the capture process is active and needs to
    guide the card user through the process or show feedback.

| channelOptions
| `WebSdk.WebChannelOptionsData`
| optional
| A channel options object from `WebSdk` library. See WebSdk documentation.

| debug
| `boolean`
| optional
| Enables to output some debug information into the console.
|===

''''''''''''''''''''''
[[CardType, CardType]]
==== `CardType`

The `CardType` value can be provided to the <<capture>> function via its `options` parameter, to restring which type of cards should be accepted.

.Definition
[separator=¦]
|===
a¦
[source,typescript]
----
type CardType = "CID" | "CW"
----
|===

.Values
[%autowidth]
|===
| Name | Description

| "CID"
| Accept Contactless ID cards

| "CW"
| Accept Contactless Writable cards
|===

If no value or null/empty value is passed into the `<<CaptureOptions>>.cardType`,
any card type will be accepted.

When a card is accepted, the type of the card used will be returned in the
<<CaptureResult>>.cardType` property. No value or null/empty value means the
card type is unknown.


''''''''''''''''''''''''''''''''''''
[[CardTech, CardTech]]
==== `CardTech`

A technology of the card presented by the user. The value is returned in the `<<CaptureResult>>.tech` property.

.Definition
[separator=¦]
|===
a¦
[source,typescript]
----
type KnownCardTech
    = "Proximity 125 kHz"
    | "iClass Legacy"
    | "MIFARE Classic"
    | "Seos"
    | "MIFARE DESFire"
    | "FeliCa Sony PaSoRi"
    | "RFIdeas"
    | "LEGIC"
    | "Card Serial Number (CSN)"

type CardTech = KnownCardTech | string
----
|===

.Values
[%autowidth]
|===
| Name | Description

| "Proximity 125 kHz"        | Proximity 125 kHz
| "iClass Legacy"            | iClass Legacy
| "MIFARE Classic"           | MiFare Classic
| "Seos"                     | SEOS
| "MIFARE DESFire"           | DesFire EV*
| "FeliCa Sony PaSoRi"       | Felica (from not PCSC-compatible Sony PaSoRi readers), CUID
| "RFIdeas"                  | Cards from RFIdeas readers, CUID
| "LEGIC"                    | Cards from not PCSC-compatible Legic readers, CUID
| "Card Serial Number (CSN)" | Card CUID from high frequency readers
|===


''''''''''''''''''''''''''''''''''''
[[FeedbackHandler, FeedbackHandler]]
==== `FeedbackHandler`

A function with the `FeedbackHandler` signature can be passed an optional feedback
via the `<<CaptureOptions>>.feedbackHandler` property.

.Definition
[separator=¦]
|===
a¦
[source,typescript]
----
type FeedbackHandler = (feedback: Feedback) => void;
----
|===

.Parameters
[cols="^1,^1,^1,10"]
|===
| Name | Type | Specs | Description

| feedback
| <<Feedback>>
| mandatory
| A feedback object.
|===

IMPORTANT: A synchronous feedback handler can throw safely,
    but it should not block the code for too long.
    +
    If the feedback handler is an async function, it must handle all its
    exceptions to avoid uncaught async exceptions.


''''''''''''''''''''''''''''''''
[[CaptureResult, CaptureResult]]
==== `CaptureResult`

The <<capture>> function returns a `CaptureResult` object (wrapped in a promise).

.Definition
[separator=¦]
|===
a¦
[source,typescript]
----
interface CaptureResult {
    readonly purpose: Purpose
    readonly cardType: CardType
    readonly tech?: CardTech
    readonly cardData: EnrollmentData | AuthenticationData
}
----
|===

.Properties
[cols="^1,^1,^1,10"]
|===
| Name | Type | Specs | Description

| purpose
| <<Purpose>>
| mandatory
| A value indicating a purpose of the card data captured.
  The `<<Purpose>>` value passed into the <<capture>> function.

| cardType
| <<CardType>>
| mandatory
| A value indicating a type of the card presented by the user.

| tech
| <<CardTech>>
| optional
| A string value indicating a technology of the card presented.

| cardData
| <<EnrollmentData>> or <<AuthenticationData>>
| mandatory
| Depending on a value of the `purpose` parameter passed to the <<capture>> function:
  +
  <<EnrollmentData>> object if "enroll" was passed;
  +
  <<AuthenticationData>> object if "auth" was passed

|===

''''''''''''''''''''''''''''''''''
[[EnrollmentData, EnrollmentData]]
==== `EnrollmentData`

The `EnrollmentData` is an object returned as the base64url-encoded string in
the `<<CaptureResult>>.Data` property when the `<<Purpose, "enroll">>` value was
passed to the <<capture>> function.

.Definition
[separator=¦]
|===
a¦
[source,typescript]
----
interface EnrollmentData
{
    readonly UID?: string
    readonly tech?: CardTech
    readonly address?: string
    readonly key?: string
    nickname?: string
}
----
|===

.Properties
[cols="^1,^1,^1,10"]
|===
| Name | Type | Specs | Description

| UID
| `string`
| optional
| A base64Url-encoded card CUID for Contactless ID (read only) card.

| tech
| <<CardTech>>
| optional
| A string value indicating a technology of the card presented.

| address
| `string`
| optional
| An address of a DP record on iClass Legacy or MiFare Classic cards;
  or other necessary card information.

| key
| `string`
| optional
| A base64url-encoded AES256 key for Contactless Writable.

| nickname
| `string`
| optional
| A card "nickname". The property contains a card technology (same as `tech`),
  but it may be modified by a user before sending to the server
  (this would require base64url decoding/encoding).

|===

.Example
|===
a|
[source,json]
----
{
  "UID": "BCxWcjoUkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "tech": "DESFire EV",
  "address":0,
  "key": "XVdVVUUzVVV1VVVVgwU0fww8bDOXGpF77cbXCh-nSbtEwO8aHO-wojoGcIg",
  "nickname":"DESFire EV"
 }
----
|===


''''''''''''''''''''''''''''''''''''''''''
[[AuthenticationData, AuthenticationData]]
==== `AuthenticationData`

The `AuthenticationData` is an object returned as the base64url-encoded string
in the `<<CaptureResult>>.Data` property when the `<<Purpose, "auth">>` value was
passed to the <<capture>> function.

.Definition
[separator=¦]
|===
a¦
[source,typescript]
----
interface AuthenticationData {
    readonly UID?: string
    readonly OTP?: string
}
----
|===

.Properties
[cols="^1,^1,^1,10"]
|===
| Name | Type | Specs | Description

| UID
| `string`
| optional
| A base64url-encoded card CUID for Contactless ID (read only).

| OTP
| `string`
| optional
| An OTP value for the authentication.

|===

.Example
|===
a|
[source,json]
----
{
  "OTP": "837167",
  "UID": "BCxWcjoUkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
}
----
|===


''''''''''''''''''''''
[[Feedback, Feedback]]
==== `Feedback`

`Feedback` values are passed into a <<FeedbackHandler>> callback function
during the capture process. Feedback values should be used to update UI
and prompt the user to do certain actions (e.g. place a card when ready) or
notify about a transient states (starting or paused) when no actions are accepted.

.Definition
[separator=¦]
|===
a¦
[source,typescript]
----
interface Feedback {
    readonly message: FeedbackMessage
    readonly code?: number
}
----
|===

.Properties
[cols="^1,^1,^1,10"]
|===
| Name | Type | Specs | Description

| message
| <<FeedbackMessage>>
| mandatory
| A prompt or notification for the user.

| code
| `number`
| optional
| An additional information passed from the native platform as `HRESULT`.
  This information may be useful for logging purposes. The API does not
  provide translation of these codes, so the API user must refer to the native
  Card SDK documentation.

|===

''''''''''''''''''''''''''''''''''''

[[FeedbackMessage, FeedbackMessage]]
==== `FeedbackMessage`

The native platform may potentially return a non-standard feedback which
cannot be translated to any of `FeedbackMessages` values. Non-standard feedback
messages will be generated using a system locale.

.Definition
[separator=¦]
|===
a¦
[source,typescript]
----
type FeedbackMessage
    = "Starting"
    | "Paused"
    | "ConnectReader"
    | "UseCard"
    | "UseDifferentCard"
    | "UseDifferentCardType"
    | "UseSingleCard"
----
|===

.Values
[%autowidth]
|===
| Name | Description

| "Starting"            | The capture process is starting
| "Paused"              | The capture process is paused (e.g. due to a lost focus)
| "ConnectReader"       | Card reader is disconnected or not found
| "UseCard"             | Generic prompt to insert/tap/swipe a card
| "UseDifferentCard"    | A card was not read or recognized
| "UseDifferentCardType"| A card of unexpected type was used
| "UseSingleCard"       | Multiple cards were used at once
|===


''''''''''''''''''''''
[[ApiError, ApiError]]
==== `ApiError`

The `ApiError` class extends a standard `Error` class with an optional numeric `code` property containing additional information passed from the native platform as `HRESULT`. This information may be useful for logging purposes. The API does not provide translation of these codes, so the API user must refer to the Card SDK documentation.

The native platform may potentially return a non-standard error which cannot be translated to any of `ErrorMessages` values. Non-standard error messages will be generated using a system locale.

.Definition
[separator=¦]
|===
a¦
[source,typescript]
----
interface ApiError extends Error
{
    readonly name = "dp.card.ApiError"
    readonly message?: ErrorMessage | string
    readonly code?: number;
}
----
|===

.Properties
[cols="^1,^1,^1,10"]
|===
| Name | Type | Specs | Description

| name
| `string`
| readonly
| A `"dp.card.ApiError"` event name constant, same for all `ApiError` instances.

| message
| <<ErrorMessage>> or `string`
| readonly
| An error message constant (used as a key for translation)
  or a system error message in a system locale.

| code
| `number`
| optional
| An error code (HRESULT).

|===


''''''''''''''''''''''''''''''
[[ErrorMessage, ErrorMessage]]
==== `ErrorMessage`

Error messages are returned in a `message` property of the <<ApiError>> object.

.Definition
[separator=¦]
|===
a¦
[source,typescript]
----
type ErrorMessage
    = "BadVersion"
    | "BadConnection"
    | "BadResponse"
    | "Aborted"
    | "Timeout"
----
|===

.Values
[%autowidth]
|===
| Name | Description

| "BadVersion"     | Incompatible client version
| "BadConnection"  | Connection failure
| "BadResponse"    | Native platform failure
| "Aborted"        | The operation was aborted by the user
| "Timeout"        | The operation was aborted due to the inactivity timeout
|===

